### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by hanjoosten** [freckle/stack-cache-action#5]
I couldn't find if you intend to support builds for windows as well. Currently, this action fails on windows, with the error message:

~~~
Error: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type undefined
~~~
Example can be found here: https://github.com/AmpersandTarski/Ampersand/runs/2658444340?check_suite_focus=true#step:3:1

**Comment by pbrisbin** [comment]
Since we delegate most of the hard work to `@actions/cache`, I think it would be feasible to keep this working on windows. We should add a matrix of the big 3 to our [example](https://github.com/freckle/stack-cache-action/blob/main/.github/workflows/example.yml) workflow to protect against regressions.

Based on [this stackoverflow](https://stackoverflow.com/questions/60234640/typeerror-err-invalid-arg-type-the-path-argument-must-be-of-type-string-re#comment117840376_60234640) this could be originating from us passing an `undefined` to `path.join`. 

I see us passing `process.env.HOME` to `path.join` [here](https://github.com/freckle/stack-cache-action/blob/dd593ec745aab94f0f3cfbb55b7671f108a8752f/src/stack-cache.test.js#L81), and expecting `$HOME` is the sort of thing that may not work on windows. As a windows users, could you confirm @hanjoosten ?

If this actually is the bug, what is the correct way to find wherever `~/.stack` is on Windows?

**Comment by pbrisbin** [comment]
@andreasabel replying here since this is the open issue and not the closed dupe.

>  For a start, I would not know how to run and test the action after I have made changes

What I would do is extend the [example / integration test](https://github.com/freckle/stack-cache-action/blob/main/.github/workflows/example.yml#L14) with a [matrix](https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#example-using-a-single-dimension-matrix) by os -- that should reproduce the error on windows and work as a regression test on anything you fix.

**Comment by nikita-volkov** [comment]
Another example: https://github.com/pgenie-tech/client-app/runs/6906233831?check_suite_focus=true
